repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-pytest
    rev: v7.4.4
    hooks:
      - id: pytest
        additional_dependencies: []
